In [1]:
# import dependencies
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt

# add citipy to library
from citipy import citipy

#add requests module
import requests

# import the API key from config.py file
from config import weather_api_key


#import datetime to recast api date to a datetime format
import time
from datetime import datetime

In [2]:
# create a random set of Latitude and longitude
#note start with set of 10 to limit API calls
lats = np.random.uniform(low=-90.000, high=90.000, size=20)
lngs = np.random.uniform(low=-180.000, high=180.000, size=20)
# the zip method combines the lats and longitudes into a list of pairs
lat_lngs = zip(lats, lngs)
lat_lngs




# add latitudes and longitudes to a list
coordinates = list(lat_lngs)

In [3]:
# random world cities
# This will require citipy to be installed to Pythondata enviroment
# will require pip install of citipy


# use citipy  module to determine city based on lat and long
#add from citpy import citipy to list of dependencies



#Create a list for  the holding of cities

cities = []
# Identify the nearest city for each latitude and longitude combination.
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name

    # If the city is unique, then we will add it to the cities list.
    if city not in cities:
        cities.append(city)
# Print the city count to confirm sufficient count.
len(cities)
#cities

#identify the nearest city for each lat and long combination

# print the city count to confirm sufficient count

20

In [4]:
# add weather api_key to config.py
#add import requests to list of dependencies

In [5]:
# starting url for weather map api call
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key
#print(url)

In [6]:
#create an empty list to hold weather data
city_data = []
# Print the beginning of the logging.
print("Beginning Data Retrieval     ")
print("-----------------------------")

# Create counters.
record_count = 1
set_count = 1
# Loop through all the cities in the list.
for i, city in enumerate(cities):

    # Group cities in sets of 50 for logging purposes.
    if (i % 50 == 0 and i >= 50):
        set_count += 1
        record_count = 1
        time.sleep(60)

    # Create endpoint URL with each city.
    city_url = url + "&q=" + city.replace(" ","+")

    # Log the URL, record, and set numbers and the city.
    print(f"Processing Record {record_count} of Set {set_count} | {city}")
    # Add 1 to the record count.
    record_count += 1
    
    #check to see if requests worked
    #print(requests.get(city_url).json())
    
    
    # Run an API request for each of the cities.
    try:
        # Parse the JSON and retrieve data.
        city_weather = requests.get(city_url).json()
        # Parse out the needed data.
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        #add current description variable
        # note: this is found imside the json object using:
        #the "weather" key
        #getting first item in list using index[0]
        # and getting the value associated with "description" key.
        current_description = city_weather["weather"][0]["description"]
        # Convert the date to ISO standard.
        city_date = datetime.utcfromtimestamp(city_weather["dt"]).strftime('%Y-%m-%d %H:%M:%S')
        # Append the city information into city_data list.
        city_data.append({"City": city.title(),
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Current Description": current_description,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Country": city_country,
                          "Date": city_date})

# If an error is experienced, skip the city.
    except:
        print("City not found. Skipping...")
        pass

# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Beginning Data Retrieval
-----------------------------
Processing Record 1 of Set 1 | illoqqortoormiut
City not found. Skipping...
Processing Record 2 of Set 1 | east london
Processing Record 3 of Set 1 | asau
Processing Record 4 of Set 1 | talnakh
Processing Record 5 of Set 1 | manzil jamil
City not found. Skipping...
Processing Record 6 of Set 1 | ketchikan
Processing Record 7 of Set 1 | namtsy
Processing Record 8 of Set 1 | thompson
Processing Record 9 of Set 1 | weyburn
Processing Record 10 of Set 1 | dikson
Processing Record 11 of Set 1 | fairview
Processing Record 12 of Set 1 | puerto ayora
Processing Record 13 of Set 1 | aklavik
Processing Record 14 of Set 1 | ribeira grande
Processing Record 15 of Set 1 | maniitsoq
Processing Record 16 of Set 1 | saint-philippe
Processing Record 17 of Set 1 | ushuaia
Processing Record 18 of Set 1 | faanui
Processing Record 19 of Set 1 | cape town
Processing Record 20 of Set 1 | maine-soroa
-----------------------------
Data Retrieval Complete
-----------------------------

In [7]:
#city_data

In [8]:
# Convert the array of dictionaries to Pandas DataFrame.
city_data_df = pd.DataFrame(city_data)
city_data_df.head(10)

,City,Lat,Lng,Current Description,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,East London,-33.0153,27.9116,broken clouds,57.63,71,72,18.19,ZA,2022-07-23 21:28:47
1,Asau,46.4333,26.4000,broken clouds,75.96,73,52,2.89,RO,2022-07-23 21:32:48
2,Talnakh,69.4865,88.3972,broken clouds,63.21,60,81,4.70,RU,2022-07-23 21:32:48
3,Ketchikan,55.3422,-131.6461,broken clouds,59.47,77,75,16.11,US,2022-07-23 21:29:05
4,Namtsy,62.7161,129.6658,clear sky,68.18,67,5,7.78,RU,2022-07-23 21:32:49
5,Thompson,55.7435,-97.8558,broken clouds,64.56,52,75,10.36,CA,2022-07-23 21:30:51
6,Weyburn,49.6668,-103.8511,broken clouds,70.02,49,81,14.97,CA,2022-07-23 21:30:14
7,Dikson,73.5069,80.5464,broken clouds,48.76,79,78,11.07,RU,2022-07-23 21:32:50
8,Fairview,40.8126,-73.9990,few clouds,93.76,29,14,10.36,US,2022-07-23 21:29:45
9,Puerto Ayora,-0.7393,-90.3518,broken clouds,78.76,89,81,5.01,EC,2022-07-23 21:32:50

In [9]:
# reorder DataFrame
new_column_order = ["City", "Country","Date","Current Description","Lat","Lng","Max Temp","Humidity","Cloudiness","Wind Speed"]
city_data_df = city_data_df[new_column_order]

#view city_data_df
city_data_df

,City,Country,Date,Current Description,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,East London,ZA,2022-07-23 21:28:47,broken clouds,-33.0153,27.9116,57.63,71,72,18.19
1,Asau,RO,2022-07-23 21:32:48,broken clouds,46.4333,26.4000,75.96,73,52,2.89
2,Talnakh,RU,2022-07-23 21:32:48,broken clouds,69.4865,88.3972,63.21,60,81,4.70
3,Ketchikan,US,2022-07-23 21:29:05,broken clouds,55.3422,-131.6461,59.47,77,75,16.11
4,Namtsy,RU,2022-07-23 21:32:49,clear sky,62.7161,129.6658,68.18,67,5,7.78
5,Thompson,CA,2022-07-23 21:30:51,broken clouds,55.7435,-97.8558,64.56,52,75,10.36
6,Weyburn,CA,2022-07-23 21:30:14,broken clouds,49.6668,-103.8511,70.02,49,81,14.97
7,Dikson,RU,2022-07-23 21:32:50,broken clouds,73.5069,80.5464,48.76,79,78,11.07
8,Fairview,US,2022-07-23 21:29:45,few clouds,40.8126,-73.9990,93.76,29,14,10.36
9,Puerto Ayora,EC,2022-07-23 21:32:50,broken clouds,-0.7393,-90.3518,78.76,89,81,5.01
10,Aklavik,CA,2022-07-23 21:32:50,light rain,68.2191,-135.0107,53.60,94,100,4.61
11,Ribeira Grande,PT,2022-07-23 21:32:51,scattered clouds,38.5167,-28.7000,75.60,88,40,10.36
12,Maniitsoq,GL,2022-07-23 21:32:51,overcast clouds,65.4167,-52.9000,45.97,84,88,6.35
13,Saint-Philippe,RE,2022-07-23 21:32:52,light rain,-21.3585,55.7679,68.97,84,55,12.15
14,Ushuaia,AR,2022-07-23 21:29:56,snow,-54.8000,-68.3000,33.46,93,100,19.57
15,Faanui,PF,2022-07-23 21:32:52,clear sky,-16.4833,-151.7500,79.56,73,9,12.91
16,Cape Town,ZA,2022-07-23 21:30:18,few clouds,-33.9258,18.4232,55.38,67,20,10.36
17,Maine-Soroa,NE,2022-07-23 21:32:53,scattered clouds,13.2114,12.0241,85.35,50,49,5.97

In [10]:
# Create the output file (CSV).
output_data_file = "Weather_Database/WeatherPy_Database.csv"
# Export the City_Data into a CSV.
city_data_df.to_csv(output_data_file, index_label="City_ID")